image: python:3.11                                        # Specify Docker image

before_script:                                            # Before Script job
  - pip install -r requirements.txt

test:                                                     # Test job
  stage: test
  script:
    - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
      - test
  except:
    - main

pages:                                                     # Tell the runner to deploy to Gitlab pages
  stage: deploy
  script:
    - mkdocs build --strict --verbose --site-dir public
  artifacts:
    paths:
      - public
  only:
    - main